#!/usr/bin/env python3
"""
Encryption utilities for securing user API keys and secrets.
Uses cryptography's Fernet symmetric encryption.
"""

import os
import logging
from cryptography.fernet import Fernet

log = logging.getLogger(__name__)

# Load encryption key from environment or fallback to temporary key for development
ENCRYPTION_KEY = os.environ.get("SaaS_ENCRYPTION_KEY")

if not ENCRYPTION_KEY:
    # Autogenerate a temporary key for dev, warn user
    temp_key = Fernet.generate_key().decode()
    log.warning(
        f"[SECURITY] SaaS_ENCRYPTION_KEY env var not set. "
        f"Using autogenerated temporary key for session: {temp_key}. "
        f"Set this key in your .env file to persist encrypted secrets across restarts!"
    )
    ENCRYPTION_KEY = temp_key

_fernet = Fernet(ENCRYPTION_KEY.encode())

def encrypt_secret(plain_text: str) -> str:
    """Encrypts a plain text string to a token string."""
    if not plain_text:
        return ""
    if plain_text.startswith("enc:"):
        return plain_text # Already encrypted
    encrypted_bytes = _fernet.encrypt(plain_text.encode())
    return "enc:" + encrypted_bytes.decode()

def decrypt_secret(encrypted_text: str) -> str:
    """Decrypts an 'enc:' prefixed token string back to plain text."""
    if not encrypted_text:
        return ""
    if not encrypted_text.startswith("enc:"):
        return encrypted_text # Plain text fallback
    try:
        encrypted_part = encrypted_text[4:]
        decrypted_bytes = _fernet.decrypt(encrypted_part.encode())
        return decrypted_bytes.decode()
    except Exception as e:
        log.error(f"Failed to decrypt secret: {e}")
        raise ValueError("Decryption failed. Confirm ENCRYPTION_KEY matches the key used to encrypt.")

if __name__ == "__main__":
    test_secret = "0xmy_private_key_hex_value"
    encrypted = encrypt_secret(test_secret)
    decrypted = decrypt_secret(encrypted)
    print("Test plain text:", test_secret)
    print("Test encrypted text:", encrypted)
    print("Test decrypted text:", decrypted)
    assert decrypted == test_secret, "Decryption check failed"
    print("Encryption test passed successfully!")
