from __future__ import annotations

from datetime import datetime, timezone

from .schemas import DOMAIN_LABELS, Domain, ResearchReport


def _domain_badge(domain: Domain) -> str:
    badges = {
        Domain.GENERAL: "General",
        Domain.ACADEMIA: "Academia",
        Domain.WORLD_NEWS: "World News",
        Domain.INDIA_STOCKS: "India Stocks",
        Domain.US_STOCKS: "US Stocks",
        Domain.CRYPTO: "Crypto",
    }
    return badges.get(domain, domain.value)


def _format_timestamp(ts: str) -> str:
    try:
        dt = datetime.fromisoformat(ts)
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except (ValueError, TypeError):
        return ts


def build_markdown(report: ResearchReport) -> str:
    lines = []
    lines.append(f"# Research Report: {report.query}")
    lines.append("")
    lines.append(
        f"> **Generated:** {_format_timestamp(report.generated_at)}  "
        f"| **Domains:** {', '.join(_domain_badge(d) for d in report.domains)}  "
        f"| **Sources:** {report.total_sources}"
    )
    lines.append("")

    if report.classifier_reasoning:
        lines.append("## Auto-Routing")
        lines.append("")
        lines.append(f"{report.classifier_reasoning}")
        lines.append("")

    if report.collector_results:
        lines.append("## Findings by Domain")
        lines.append("")

        for cr in report.collector_results:
            lines.append(f"### {_domain_badge(cr.domain)}")
            lines.append("")
            lines.append(cr.summary)
            lines.append("")

            if cr.top_insights:
                lines.append("**Key Insights:**")
                lines.append("")
                for ins in cr.top_insights:
                    lines.append(f"- {ins}")
                lines.append("")

            if cr.theme_groups:
                for tg in cr.theme_groups:
                    lines.append(f"**{tg.name}** — {len(tg.sources)} source(s)")
                    for src in tg.sources:
                        lines.append(f"- [{src.title}]({src.url})")
                        if src.key_points:
                            kp = src.key_points[0].strip()[:250]
                            lines.append(f"  > {kp}")
                        if src.published:
                            lines.append(f"  *({src.published})*")
                    lines.append("")

    lines.append("---")
    lines.append("")

    if report.synthesis:
        lines.append("## Synthesis & Conclusion")
        lines.append("")
        lines.append(report.synthesis)
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        f"*Report generated by research-agent at {_format_timestamp(report.generated_at)}. "
        f"Always verify critical data points from primary sources.*"
    )
    lines.append("")

    return "\n".join(lines)
